name: 'Verify Branches and PRs'

on:
  push:

jobs:
  build-and-verify:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          # Codecov needs fetch-depth > 1
          fetch-depth: 2
      - name: 'Set up JDKs'
        uses: ./.github/actions/setup-build-env
        with:
          additional-java-version: 8
      - name: 'Build Spock'
        # secrets are not injected for pull requests
        env:
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.SPOCK_BUILD_CACHE_USERNAME }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.SPOCK_BUILD_CACHE_PASSWORD }}
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-parallel --stacktrace build codeCoverageReport "-Dvariant=2.5" "-DjavaVersion=8"
